base:
    seed: &seed 0
model:
    type: Qwen25VL_V4
    path: input_path 
    torch_dtype: torch.float32
calib:
    name: wikitext2
    download: False
    path: /workspace/zhangl98@xiaopeng.com/dataset/calib/wikitext2/
    n_samples: 512
    bs: 32
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
  - eval_pos: [fake_quant]
    name: wikitext2
    type: ppl
    download: False
    path: /workspace/zhangl98@xiaopeng.com/dataset/eval/wikitext2/
    seq_len: 2048
    bs: 1
    inference_per_block: False
  - eval_pos: [fake_quant]
    type: vqa
    name: [mmmu]
    download: False
    path: /workspace/lim42@xiaopeng.com/dataset/mme/
    bs: 1
    limit: 200  # Limit test num for evaluation
    inference_per_block: False
# ignored_layers:
#     block_ids: [0-28]
#     layer_names: ["mlp.down_proj"]
quant:
    # vision:
    #     method: RTN
    #     weight:
    #         bit: 4
    #         symmetric: True
    #         granularity: per_channel
    #         group_size: -1
    #         calib_algo: minmax
    #     act:
    #         bit: 16
    #         symmetric: True
    #         granularity: per_token
    language:
        method: RTN
        weight:
            bit: 4
            symmetric: True
            granularity: per_channel
            group_size: -1
            calib_algo: mse
        act:
            bit: 16
            symmetric: True
            granularity: per_tensor
save:
    # save_trans: True
    save_fake: True
    save_path: out_path 