base:
    seed: &seed 0
model:
    type: Qwen25VL_V4
    path: input_path 
    torch_dtype: torch.float32
calib:
    name: wikitext2
    download: False
    path: /workspace/zhangl98@xiaopeng.com/dataset/calib/wikitext2/
    n_samples: 512
    bs: 32
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    - 
        eval_pos: [fake_quant]
        type: v4
        name: mmmu
        download: False
        path: ./xq_eval/datasets_v4/mmmu_val_98_test_368length.json
        limit: -1
        bs: 1
        seq_len: 768
        seed: *seed
    - 
        eval_pos: [fake_quant]
        type: v4
        name: V4_decision
        download: False
        path: ./xq_eval/datasets_v4/V15_all_new.json
        limit: -1
        bs: 1
        seq_len: 2048
        seed: *seed
        special:
            sptk_map_path: ./xq_eval/datasets_v4/V15_DEMO.sptk_map.json
    - 
        eval_pos: [fake_quant]
        type: v4
        name: feedback
        download: False
        path: ./xq_eval/datasets_v4/val_memory_v3_002.json
        limit: -1
        bs: 1
        seq_len: 2048
        seed: *seed
    - 
        eval_pos: [fake_quant]
        type: v4
        name: oms
        download: False
        path: ./xq_eval/datasets_v4/test_v2_6_mixed_refined_0617v6-相对坐标-right-560px.json
        limit: -1
        bs: 1
        seq_len: 2048
        seed: *seed
    - 
        eval_pos: [fake_quant]
        type: v4
        name: alpaca
        download: False
        path: ./xq_eval/datasets_v4/alpaca_zh_data_100_test.json
        limit: -1
        bs: 1
        seq_len: 2048
        seed: *seed
    # - 
    #     eval_pos: [fake_quant]
    #     type: v4
    #     name: vqa
    #     download: False
    #     path: ./xq_eval/datasets_v4/test_data_yans2_v7_no_intersection_normalized_v3_198.json
    #     limit: -1
    #     bs: 1
    #     seq_len: 2048
    #     seed: *seed
# ignored_layers:
#     block_ids: [0-28]
#     layer_names: ["mlp.down_proj"]
quant:
    # vision:
    #     method: RTN
    #     weight:
    #         bit: 4
    #         symmetric: True
    #         granularity: per_channel
    #         group_size: -1
    #         calib_algo: minmax
    #     act:
    #         bit: 16
    #         symmetric: True
    #         granularity: per_token
    language:
        method: RTN
        weight:
            bit: 8
            symmetric: True
            granularity: per_channel
            group_size: -1
            calib_algo: mse
        act:
            bit: 8
            symmetric: True
            granularity: per_tensor
# save:
#     # save_trans: True
#     save_fake: True
#     save_path: out_path 