base:
    seed: &seed 0
model:
    type: Qwen25VL
    path: /workspace/lim42@xiaopeng.com/binary_data/pytorch_models/Qwen2.5-VL-7B-Instruct
    tokenizer_mode: slow
    torch_dtype: auto
eval:
    eval_pos: [pretrained, transformed, fake_quant]
    name: wikitext2
    download: True
    path: eval data path
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: False
        granularity: per_channel
        group_size: -1
        calib_algo: minmax
    act:
        bit: 8
        symmetric: False
        granularity: per_tensor
    kvcache:
        method: Naive
        bit: 8
        symmetric: False
        granularity: per_token
        group_size: 128
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: True
save:
    # Save the Quarot-transformed model.
    save_trans: True
    save_fake: False
    save_path: /code/lim42@xiaopeng.com/llmc_test/work/out_qwen25vl_quarot_w8a8_step1/
