base:
    seed: &seed 0
model:
    type: Qwen3Moe
    path: /workspace/gaoy25@xiaopeng.com/dataset/Qwen3-30B-A3B
    tokenizer_mode: slow
    torch_dtype: auto
eval:
    type: ppl
    eval_pos: [transformed, fake_quant]
    name: wikitext2
    download: False
    path: /workspace/gaoy25@xiaopeng.com/leizhang/dataset/eval/wikitext2
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
        calib_algo: minmax
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: False
save:
    # Save the Quarot-transformed model.
    save_trans: False
    save_fake: False
    save_path: /code/zhangl98@xiaopeng.com/llmc_test/work/out_qwen3moe_quarot
