base:
    seed: &seed 0
model:
    type: Qwen3Omni
    path: /dataset/workspace/lim42/models/Qwen3-Omni-30B-A3B-Instruct/
    tokenizer_mode: slow
    torch_dtype: auto
eval:
#   - eval_pos: [pretrain,transformed,fake_quant]
#     type: vqa
#     name: [mme]
#     download: False
#     path: /workspace/lim42@xiaopeng.com/dataset/mme/
#     bs: 1
#     limit: 100  # Limit test num for evaluation
#     inference_per_block: False
  - eval_pos: [pretrain,transformed,fake_quant]
    name: wikitext2
    type: ppl
    download: True
    path: ""
    seq_len: 2048
    bs: 1
    inference_per_block: False
quant:
    audio:
        method: QuarotOmni
        weight:
            bit: 8
            symmetric: True
            granularity: per_channel
            group_size: -1
            calib_algo: minmax
        act:
            bit: 8
            symmetric: True
            granularity: per_token
        special:
            rotate_mode: hadamard
            fp32_had: True
            online_rotate: False
    vision:
        method: QuarotOmni
        weight:
            bit: 8
            symmetric: True
            granularity: per_channel
            group_size: -1
            calib_algo: minmax
        act:
            bit: 8
            symmetric: True
            granularity: per_token
        special:
            rotate_mode: hadamard
            fp32_had: True
            online_rotate: False
    language:
        method: Quarot
        weight:
            bit: 8
            symmetric: True
            granularity: per_channel
            group_size: -1
            calib_algo: minmax
        act:
            bit: 8
            symmetric: True
            granularity: per_token
        special:
            rotate_mode: hadamard
            fp32_had: True
            online_rotate: False
save:
    # Save the Quarot-transformed model.
    save_trans: True
    save_fake: False
    save_path: /code/lim42@xiaopeng.com/qwen3omini_vision_quarot
